I_love_point_clouds_Q4: I_love_point_clouds_Q4.o
	gcc -Wall -D_REENTRANT I_love_point_clouds_Q4.o -o I_love_point_clouds_Q4 -lrt -lpthread -lm

I_love_point_clouds_Q4.o: I_love_point_clouds_Q4.c
	gcc -Wall -c  I_love_point_clouds_Q4.c -o I_love_point_clouds_Q4.o -lm
