I_love_point_clouds_Q1: I_love_point_clouds_Q1.o
	gcc -Wall -D_REENTRANT I_love_point_clouds_Q1.o -o I_love_point_clouds_Q1 -lrt -lpthread -lm

I_love_point_clouds_Q1.o: I_love_point_clouds_Q1.c
	gcc -Wall -c  I_love_point_clouds_Q1.c -o I_love_point_clouds_Q1.o -lm
