I_love_point_clouds_Q2: I_love_point_clouds_Q2.o
	gcc -Wall -D_REENTRANT I_love_point_clouds_Q2.o -o I_love_point_clouds_Q2 -lrt -lpthread -lm

I_love_point_clouds_Q2.o: I_love_point_clouds_Q2.c
	gcc -Wall -c  I_love_point_clouds_Q2.c -o I_love_point_clouds_Q2.o -lm
