I_love_point_clouds_Q5: I_love_point_clouds_Q5.o
	gcc -Wall -D_REENTRANT I_love_point_clouds_Q5.o -o I_love_point_clouds_Q5 -lrt -lpthread -lm

I_love_point_clouds_Q5.o: I_love_point_clouds_Q5.c
	gcc -Wall -c  I_love_point_clouds_Q5.c -o I_love_point_clouds_Q5.o -lrt -lpthread -lm
